In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Phising_Training_Dataset.csv')
test = pd.read_csv('Phising_Testing_Dataset.csv')
data.head()

,key,having_IP,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,12344,-1,1,1,1,-1,-1,-1,-1,-1,...,1,1,-1,-1,-1,-1,1,1,-1,-1
1,12345,1,1,1,1,1,-1,0,1,-1,...,1,1,-1,-1,0,-1,1,1,1,-1
2,12346,1,0,1,1,1,-1,-1,-1,-1,...,1,1,1,-1,1,-1,1,0,-1,-1
3,12347,1,0,1,1,1,-1,-1,-1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
4,12348,1,0,-1,1,1,-1,1,1,-1,...,-1,1,-1,-1,0,-1,1,1,1,1

In [3]:
target = data.iloc[:,-1]
train = data.iloc[:,1:-1]
key = test[['key']]
test = test.iloc[:,1:]

In [4]:
# split dataset
# from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier
from matplotlib import pyplot
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train = sc.fit_transform(train)
test = sc.transform(test)

In [5]:
# from sklearn.model_selection import RandomizedSearchCV
# distributions = dict(n_estimators=[10,100,400,1000,4000,10000, 15000], 
#                     loss=['exponential'], learning_rate= [1.0,0.1,0.01],
#                     max_depth=[3,7,31], min_samples_split=[2,5],max_features=['auto',30])
# gbc = GradientBoostingClassifier(random_state=0)
# clf = RandomizedSearchCV(gbc, distributions, random_state=0, n_jobs = -1, cv = 3, verbose = 3)

In [6]:
# search = clf.fit(train, target)
# yhat = clf.predict(test)
# print(search.best_params_)

In [7]:
model = GradientBoostingClassifier(n_estimators = 15000, max_features =  'auto', learning_rate = 0.1, random_state=0)
model.fit(train,target)
yhat = model.predict(test)

In [8]:
df = pd.DataFrame()
df['key'] = key
df['Result'] = yhat
df

        key  Result
0     21338       1
1     21339      -1
2     21340      -1
3     21341      -1
4     21342       1
...     ...     ...
2095  23433       1
2096  23434       1
2097  23435      -1
2098  23436       1
2099  23437       1

[2100 rows x 2 columns]

In [9]:
df.to_csv('submission.csv',index=False)